# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-af253472-b674-46a5-85bc-4bbdec3f54fe";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."luks-af253472-b674-46a5-85bc-4bbdec3f54fe".device =
    "/dev/disk/by-uuid/af253472-b674-46a5-85bc-4bbdec3f54fe";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-af253472-b674-46a5-85bc-4bbdec3f54fe";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C5AA-F8F6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/mapper/luks-23b6cf5a-71c7-40a2-b74b-271e45d819a8";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-23b6cf5a-71c7-40a2-b74b-271e45d819a8".device =
    "/dev/disk/by-uuid/23b6cf5a-71c7-40a2-b74b-271e45d819a8";

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/bcae511b-889d-4bc3-ad43-58fcd8aa63d0";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
