general {
    after_sleep_cmd=hyprctl dispatch dpms on
    before_sleep_cmd=loginctl lock-session
    lock_cmd=/run/current-system/sw/bin/lock-session
}

listener {
    on-timeout=loginctl lock-session
    timeout=300
}
