general {
    after_sleep_cmd=hyprctl dispatch dpms on
    before_sleep_cmd=dms ipc call lock lock
    lock_cmd=dms ipc call lock lock
}

listener {
    on-timeout=loginctl lock-session
    timeout=300
}
