font_family JetBrainsMono Nerd Font
font_size 11

shell_integration no-rc

active_tab_background #43435a
active_tab_foreground #bdc3df
background #1f1f2a
bold_font auto
bold_italic_font auto
color0 #43435a
color1 #ff568e
color10 #73de8a
color11 #f3ff85
color12 #85b6ff
color13 #a481f7
color14 #71c2d9
color15 #ebebff
color2 #64de83
color3 #efff73
color4 #73a9ff
color5 #946ff7
color6 #62c6da
color7 #dedeff
color8 #53536b
color9 #ff69a2
cursor #bdc3df
cursor_text_color #1f1f2a
foreground #bdc3df
inactive_tab_background #1f1f2a
inactive_tab_foreground #dedeff
italic_font auto
selection_background #bdc3df
selection_foreground #1f1f2a
tab_bar_background #1f1f2a
url_color #85b6ff
